apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: split-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: {{ .Values.splitIngress.hostName }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: split-client
                port:
                  number: 80
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: split-api
                port:
                  number: 3000
  tls:
    - hosts:
        - {{ .Values.splitIngress.hostName }}
      secretName: split-ssl
